name: Build Android APK (React Native)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (required for React Native)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Node.js dependencies
      - name: Install dependencies
        run: yarn install

      # Set up JDK 17 (required for Android builds)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up the Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools-version: '31.0.0'
          ndk: '21.4.7075529'

      # Run Gradle build to generate the APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      # Rename the APK to include the commit hash
      - name: Rename APK
        run: |
          cd android/app/build/outputs/apk/release/
          mv app-release.apk app-nightly-build-${{ github.sha }}.apk

      # Upload the renamed APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-nightly-build-${{ github.sha }}
          path: android/app/build/outputs/apk/release/app-nightly-build-${{ github.sha }}.apk
